### ISSUE TITLE
Order is not working

### ISSUE THREAD

**Issue by rdoursenaud** [saltstack-formulas/mounts-formula#1]
I'm trying to use a pillar like that:
```yaml
mounts:
  mounted:
    data:
      name: /mnt/data
      device: /dev/sdb
      order: 1
    cache:
      name: /mnt/data/cache
      device: tmpfs
      fstype: tmpfs
      order: last
```

For this to work, the cache must be mounted *after* the data since the cache mount point is under it.

But for whatever reason, cache is always mounted before and fails. If I add `mkmnt: True`, then it does not fail but is inaccessible since it's mounted first. I tried using `order` and `require` to no avail.

Am I missing something?
